from django.db import models
from .custom_fields import FiveDigitCodeField
from django.shortcuts import render
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.


class Author(models.Model):#Model is a class that defines the structure of the database table
    id = models.AutoField(primary_key=True)  # AutoField is a primary key that is automatically generated by the database
    name = models.CharField(max_length=100, unique=True, verbose_name="Product Name")  # unique field and text field & verbose_name is the name of the field that will be displayed in the admin panel
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)  # Decimal numbers & default value if nothing is provided
    in_stock = models.BooleanField(default=True)  # True/False
    description = models.TextField(null=True, blank=True)  # Large text & null=True, blank=True means that the field is optional
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp
      
    def __str__(self):
        return self.name


#  One-to-One relationship - Author biography using OneToOneField
class AuthorBio(models.Model):
    author = models.OneToOneField(Author, on_delete=models.CASCADE)
    bio_text = models.TextField()

    def __str__(self):
        return f"{self.author.name}'s Biography"


# many to many relationship - Genre model
class  Genre(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

# A book can belong to multiple genres → e.g., Harry Potter can be Fantasy and Adventure.
# A genre can have many books → e.g., Fantasy genre has Harry Potter 1, Harry Potter 2, etc.
# That’s why it’s called Many-to-Many.


# one to many relationship - 
class Books(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE) #this shows a drop down menu of the authors in the database
    genres = models.ManyToManyField(Genre, related_name='books') #this shows a drop down menu of the genres in the database
 

    def __str__(self):
        return f"{self.title} by {self.author.name}"
    


class Organization(models.Model):
    name = models.CharField(max_length=100, unique=True)
    max_requests = models.PositiveIntegerField(default=10)  # max requests allowed
    time_window = models.PositiveIntegerField(default=300)  # time window in seconds

    def __str__(self):
        return self.name



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.user.username} Profile"
